### PR TITLE
add --power-off arg to pikvm-update.sh

### PR DESCRIPTION
**Pull request by phedoreanu**
This PR adds the `--power-off` arg to `pikvm-update.sh`.

### CODE REVIEW

**Comment by mdevaev** [comment]
Hello. Why you need this? If you perform poweroff, Pi will not recover itself after this. Only V3 and V4 devices can do this.

**Comment by phedoreanu** [comment]
Hey, Because I have my v4 on a smart socket and I usually update it and shut it down, instead of waiting for a reboot or press ctrl + c and run poweroff.

**Comment by mdevaev** [comment]
Okay, sounds reasonable.

**Comment by mdevaev** [comment]
Released and available via update.

**Comment by phedoreanu** [comment]
Follow-up: the self-update re-exec dropped `--power-off`, so a run that self-updates would reboot instead of powering off. Fixed in #14.

**Pull request merged**
